version: "3.9"
services:
  webapi:
    image: webapi
    container_name: web_api_application
    ports:
      - "5001:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    platform: linux/amd64
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password